### ISSUE TITLE
TickProfiler Error MC 1.10.2

### ISSUE THREAD

**Issue by pantheis** [MinimallyCorrect/TickProfiler#61] opened 2017-01-20 05:57 UTC
Having some regular pauses on the server and they are getting annoying. Went looking for a profiler to see if I could diagnose what's causing the problem. When loading TickProfiler-1.10.2.jenkins.24.jar from your Jenkins build server onto the server and starting it, getting the following error as shown in the FML server log below. Any ideas?

http://paste.ubuntu.com/23831914/

**Comment by LunNova** [comment] 2017-01-20 12:10
Issue confirmed, caused by ModPatcher changes https://github.com/nallar/ModPatcher/commit/32c1d3cf7b57882f96a28ef2c542b1fe8404235c

**Comment by LunNova** [comment] 2017-01-20 13:55
Fixed by e647e6ab61d3d5cb7

**Closed as completed by LunNova** 2017-01-20 13:55 UTC
Labels: bug, 1.10.2

**Comment by pantheis** [comment] 2017-01-21 01:27
Just wanted to say thank you! Confirmed fixed and this is exactly what I'll need to track down the issues on my server.
